import type { District, Indicator } from './types';

export const INDICATORS: Indicator[] = [
  { id: 'T1', name: 'Разгрузка дорог', direction: 'transport', weight: 0.1 },
  {
    id: 'T2',
    name: 'Доступность общественного транспорта',
    direction: 'transport',
    weight: 0.1,
  },
  { id: 'E1', name: 'Озеленение', direction: 'ecology', weight: 0.09 },
  { id: 'E2', name: 'Качество воздуха', direction: 'ecology', weight: 0.11 },
  { id: 'S1', name: 'Школы и детсады', direction: 'social', weight: 0.11 },
  {
    id: 'S2',
    name: 'Поликлиники и первичная медпомощь',
    direction: 'social',
    weight: 0.11,
  },
  { id: 'B1', name: 'Безопасность улиц', direction: 'safety', weight: 0.09 },
  {
    id: 'B2',
    name: 'Безопасность дорожного движения',
    direction: 'safety',
    weight: 0.09,
  },
  { id: 'C1', name: 'Надёжность ЖКХ', direction: 'services', weight: 0.1 },
  {
    id: 'C2',
    name: 'Скорость решения обращений жителей',
    direction: 'services',
    weight: 0.1,
  },
];

export const DISTRICTS: District[] = [
  {
    id: 'yesil',
    name: 'Есиль',
    population: 0.27,
    profile: 'Богатый, но с пробками на мостах и переполненными школами.',
    indicators: {
      T1: 45,
      T2: 62,
      E1: 68,
      E2: 72,
      S1: 48,
      S2: 55,
      B1: 78,
      B2: 60,
      C1: 75,
      C2: 70,
    },
  },
  {
    id: 'almaty',
    name: 'Алматы',
    population: 0.24,
    profile: 'Старый ЖКХ и пробки.',
    indicators: {
      T1: 40,
      T2: 75,
      E1: 50,
      E2: 55,
      S1: 60,
      S2: 65,
      B1: 62,
      B2: 52,
      C1: 50,
      C2: 60,
    },
  },
  {
    id: 'saryarka',
    name: 'Сарыарка',
    population: 0.2,
    profile: 'Смог от частного сектора, слабое озеленение.',
    indicators: {
      T1: 50,
      T2: 70,
      E1: 42,
      E2: 40,
      S1: 62,
      S2: 68,
      B1: 58,
      B2: 55,
      C1: 45,
      C2: 55,
    },
  },
  {
    id: 'baikonur',
    name: 'Байконур',
    population: 0.13,
    profile: 'Середняк без ярких перекосов.',
    indicators: {
      T1: 52,
      T2: 68,
      E1: 55,
      E2: 50,
      S1: 58,
      S2: 60,
      B1: 52,
      B2: 58,
      C1: 55,
      C2: 58,
    },
  },
  {
    id: 'nura',
    name: 'Нура',
    population: 0.16,
    profile: 'Главный аутсайдер по соцсфере и транспорту.',
    indicators: {
      T1: 55,
      T2: 40,
      E1: 45,
      E2: 65,
      S1: 38,
      S2: 35,
      B1: 55,
      B2: 50,
      C1: 60,
      C2: 50,
    },
  },
];
